Vagrant.configure("2") do |config|

    # Web01 Ubuntu 20.04
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.42"
    end
  
    # Web02 Ubuntu 20.04
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64"
      web02.vm.hostname = "web02"
      web02.vm.network "private_network", ip: "192.168.56.44"
    end
  
    # DB01 CentOS 7
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.56.45"
  
      db01.vm.provision "shell", inline: <<-SHELL
          # Example: Install and configure MySQL
          sudo yum install -y mariadb-server -y
          sudo systemctl start mariadb
          sudo systemctl enable mariadb
          # Additional configurations can be added here
      SHELL
    end
  end
  